version: "3.8"

services:
  app:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - mongo
    networks:
      - eshop_net

  mongo:
    image: mongo:5.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - eshop_net
    volumes:
      - mongo_data:/data/db

networks:
  eshop_net:

volumes:
  mongo_data:
