version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - mongodb

volumes:
  mongo_data: